
services:
  db:
    image: postgres:16
    container_name: goomer_db
    restart: always
    environment:
      POSTGRES_USER: goomer
      POSTGRES_PASSWORD: goomer
      POSTGRES_DB: goomer_menu
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: goomer_api
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://goomer:goomer@db:5432/goomer_menu
      NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data:
